// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rotational_invariance_v3.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace RI {
  public static partial class ROIService
  {
    static readonly string __ServiceName = "RI.ROIService";

    static readonly grpc::Marshaller<global::RI.Image> __Marshaller_Image = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RI.Image.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RI.ROI> __Marshaller_ROI = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RI.ROI.Parser.ParseFrom);

    static readonly grpc::Method<global::RI.Image, global::RI.ROI> __Method_GetROI = new grpc::Method<global::RI.Image, global::RI.ROI>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetROI",
        __Marshaller_Image,
        __Marshaller_ROI);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RI.RotationalInvarianceV3Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ROIService</summary>
    public abstract partial class ROIServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::RI.ROI> GetROI(global::RI.Image request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ROIService</summary>
    public partial class ROIServiceClient : grpc::ClientBase<ROIServiceClient>
    {
      /// <summary>Creates a new client for ROIService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ROIServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ROIService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ROIServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ROIServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ROIServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::RI.ROI GetROI(global::RI.Image request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetROI(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::RI.ROI GetROI(global::RI.Image request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetROI, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::RI.ROI> GetROIAsync(global::RI.Image request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetROIAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::RI.ROI> GetROIAsync(global::RI.Image request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetROI, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ROIServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ROIServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ROIServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetROI, serviceImpl.GetROI).Build();
    }

  }
  public static partial class ImageService
  {
    static readonly string __ServiceName = "RI.ImageService";

    static readonly grpc::Marshaller<global::RI.Null> __Marshaller_Null = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RI.Null.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RI.Image> __Marshaller_Image = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RI.Image.Parser.ParseFrom);

    static readonly grpc::Method<global::RI.Null, global::RI.Image> __Method_GetImage = new grpc::Method<global::RI.Null, global::RI.Image>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetImage",
        __Marshaller_Null,
        __Marshaller_Image);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RI.RotationalInvarianceV3Reflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of ImageService</summary>
    public abstract partial class ImageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::RI.Image> GetImage(global::RI.Null request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ImageService</summary>
    public partial class ImageServiceClient : grpc::ClientBase<ImageServiceClient>
    {
      /// <summary>Creates a new client for ImageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ImageServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ImageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ImageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ImageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ImageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::RI.Image GetImage(global::RI.Null request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetImage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::RI.Image GetImage(global::RI.Null request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetImage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::RI.Image> GetImageAsync(global::RI.Null request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetImageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::RI.Image> GetImageAsync(global::RI.Null request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetImage, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ImageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ImageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ImageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetImage, serviceImpl.GetImage).Build();
    }

  }
}
#endregion
